---
- hosts: all
  become: true
  tasks:

  # Ubuntu
    - name: install nginx and php package
      package:
        name: 
          - "{{ server }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes



