---
- hosts: all
  become: true
  tasks:
  
# Ubuntu
    - name: update Ubuntu
      apt:
        name: 
          - nginx
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

# Centos
    - name: update Centos
      yum:
        name: 
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

 #web_servers     

- hosts: web_servers
  become: true
  tasks:

    - name: install nginx and php package
      apt:
        name: 
          - nginx
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

# db_servers      

- hosts: db_servers
  become: true
  tasks:

    - name: install httpd and php package
      yum:
        name: 
          - httpd
          - php
          - mariadb
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"