---
- hosts: all
  become: true
  tasks:
  
# Ubuntu
    - name: update Ubuntu
      tags: update always
      apt:
        name: 
          - nginx
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      

# Centos
    - name: update Centos
      tags: update always
      yum:
        name: 
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

    #playbook for adding users
- hosts: all
  become: true
  tasks:
  
    - name: add user
      tags: always
      user:
        name: mike
        groups: root
        
        
 #web_servers     

- hosts: web_servers
  become: true
  tasks:

    - name: install nginx and php package
      tags: nginx, php 
      apt:
        name: 
          - nginx
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"


# db_servers      

- hosts: db_servers
  become: true
  tasks:

    - name: install httpd and php package
      tags: httpd (server), mariadb (database) 
      yum:
        name: 
          - httpd
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

    #playbook for managing services
    - name: copy default html for site  
      tags: apache, centos, httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"


    #playbook for managing files
    - name: copy default html for site
      tags: apache, apache2, httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      # when: ansible_distribution == "Ubuntu"
